version: '3.9'
services:
  readme.file-vault.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.file-vault.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.mongo.file-vault:/data/db

volumes:
  readme.mongo.file-vault: